language: cpp

addons:
  apt:
    packages:
    - cmake
    - libmuparser-dev

script:
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local .
  - make install -j2
  - make tests -j2
  - ctest -j2 --output-on-failure
